[package]
name = "day-07"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mike@langeraar.net>"]
edition = "2021"

[dependencies]
rustc-hash = "1.1.0"
runner = { path = "../runner", version = "0.1" }
