[package]
name = "day-14"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mike@langeraar.net>"]
edition = "2021"

[dependencies]
runner = { path = "../runner", version = "0.1" }
itertools = "0.10"
