#
# Make sure we use the entire instructionset of the current CPU.
#

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]

[target.x86_64-apple-darwin]
rustflags = ["-Ctarget-cpu=native"]
