[package]
name = "day-05"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mike@langeraar.net>"]
edition = "2021"

[dependencies]
scan_fmt = "0.2.6"
runner = { path = "../runner", version = "0.1" }
